version: "3.8"
services:
  wekeep:
    image: ghcr.io/cicbyte/wekeep:latest
    container_name: wekeep
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./manifest/config:/app/manifest/config
      - ./data:/data
    networks:
      - wekeep-network

networks:
  wekeep-network:
    driver: bridge
    name: wekeep-network
